version: '3.8'

services:
  deepwiki:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # API port
      - "3000:3000"  # Next.js port
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SERVER_BASE_URL=http://localhost:8001
      - NEXT_PUBLIC_SERVER_BASE_URL=http://localhost:8001
    volumes:
      - ~/.adalflow:/root/.adalflow  # Persist repository and embedding data
    # Resource limits for docker-compose up (not Swarm mode)
    mem_limit: 6g
    mem_reservation: 2g
